# Copyright (c) 2019-2020-2021 Luca Cappa
# Released under the term specified in file LICENSE.txt
# SPDX short identifier: MIT
#
# The peculiarity of this workflow is that assumes vcpkg stored as a submodule of this repository.
# This workflow does the following:
# - Restores vcpkg artifacts from cache.
# - Sets up vcpkg if needed. Will automatically run vcpkg to install dependencies
#   described by the vcpkg.json manifest file. It will be a no-op if those are restored from cache.

name: vcpkg

inputs:
  triplet:
    required: true
  list_workspace:
    default: "false"
    required: false
outputs: {}

runs: 
  using: "composite"
      
  steps:
    - name: Setup cmake
      uses: lukka/get-cmake@latest
        
    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      id: runvcpkg
      with:
        vcpkgJsonGlob: 'vcpkg.json'
      env:
        VCPKG_DEFAULT_TRIPLET: ${{ inputs.triplet }}
    
    - name: Run CMake (consuming CMakePreset.json and vcpkg.json by vcpkg)
      uses: lukka/run-cmake@v10
      id: runcmake
      with:
        configurePreset: 'vcpkg'
        configurePresetAdditionalArgs: '[`-DVCPKG_TARGET_TRIPLET=${{ inputs.triplet }}`]'
      env:
        VCPKG_DEFAULT_TRIPLET: ${{ inputs.triplet }}
    
    - name: List $RUNNER_WORKSPACE
      if: ${{ inputs.list_workspace }}
      run: find $RUNNER_WORKSPACE
      shell: bash
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.triplet }}
        path: vcpkg_installed/${{ inputs.triplet }}/*
        if-no-files-found: error
